retrieval_methods:
  - name: "chroma"                  # Retrieval method using a dense vector store
    type: "dense"
    embedding_model: "nomic-embed-text"       # Embedding model to create vector representations

  - name: "bm25"                    # Retrieval method using BM25 for sparse retrieval
    type: "sparse"

  - name: "hybrid"                  # Combine dense and sparse retrieval scores
    type: "hybrid"
    dense_embedding_model: "ollama" # Embedding model for the dense part of hybrid retrieval

generative_models:
  - name: "nemotron-mini:latest"    # Generative model for response generation
  - name: "llama3.2:1b"             # Generative model for response generation    
  - name: "qwen2.5:3b"           # Generative model for response generation
  - name: "llama3.2:latest"
  - name: "gemma2:latest"


query_params:
  k: 5                              # Number of documents to retrieve
  temperature: 0.7                  # Temperature for response generation